### PR TITLE
1.0.5

### PR DESCRIPTION
**Pull request by 8beeeaaat**
https://github.com/8beeeaaat/web-ant-plus/pull/6

### CODE REVIEW

**Comment by Abasz** [comment]
Can you please check the npm package? I think the dist folder is missing: https://www.npmjs.com/package/web-ant-plus?activeTab=code so its not installable

**Comment by Abasz** [comment]
I just wanted to mention again that the updated 1.0.5 npm package is broken, as the src folder is not included. So upon install nothing works.

**Comment by 8beeeaaat** [comment]
@Abasz 
Sorry for the delay in replying.
In conclusion, there is no reason to include the development source in the NPM package, so I will not include it.

https://github.com/8beeeaaat/web-ant-plus/issues/9#issuecomment-2244060121

**Comment by Abasz** [comment]
I meant the dist folder not the src. Sorry. Src is of course not necessary.

**Comment by 8beeeaaat** [comment]
@Abasz 

I checked and sure enough, 1.0.5 does not include the dist directory either.
I'm very sorry about this.Thank you for your report!

https://www.npmjs.com/package/web-ant-plus/v/1.0.5?activeTab=code

**Pull request merged**
